FROM openjdk:17-jdk-oraclelinux8

RUN microdnf install findutils git

ARG USER=judice
ARG MAVEN_VERSION=3.8.6
ARG USER_HOME_DIR=/home/$USER
ARG APP_HOME=$USER_HOME_DIR/app
ARG SHA=f790857f3b1f90ae8d16281f902c689e4f136ebe584aba45e4b1fa66c80cba826d3e0e52fdd04ed44b4c66f6d3fe3584a057c26dfcac544a60b301e6d0f91c26
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries
ARG MAVEN_HOME_DIR=$USER_HOME_DIR/maven

ENV QUARKUS_LAUNCH_DEVMODE=true
ENV JAVA_ENABLE_DEBUG=true
ENV MAVEN_HOME=$MAVEN_HOME_DIR
ENV MAVEN_CONFIG="$USER_HOME_DIR/.m2"

RUN useradd -ms /bin/bash $USER \
  && mkdir -p $APP_HOME \
  && mkdir -p $MAVEN_HOME_DIR $MAVEN_HOME_DIR/ref \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha512sum -c - \
  && tar -xzf /tmp/apache-maven.tar.gz -C $MAVEN_HOME_DIR --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s $MAVEN_HOME_DIR/bin/mvn /usr/bin/mvn

COPY ./infra/api/maven/install.sh $USER_HOME_DIR
COPY ./app/api/src/main/docker/maven/mvn-entrypoint.sh $USER_HOME_DIR
COPY ./app/api/src/main/docker/maven/settings-docker.xml $MAVEN_HOME_DIR/ref/

WORKDIR $USER_HOME_DIR

USER $USER

ENTRYPOINT ["/home/judice/install.sh"]